name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2

      - run: |
          gradle --info test
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2

      - uses: github/codeql-action/init@v2
        with:
          languages: java

      - run: |
          gradle --info build -x test

      - uses: github/codeql-action/analyze@v2