name: Pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/test.yaml
  snapshot:
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/gradle-build-action@v3

      - name: release jar
        run: |
          VERSION=$(git rev-parse --short HEAD)
          gradle publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace -P version=$VERSION
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
