name: Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: opencl
        run: |
          sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd clinfo
          clinfo

      - uses: browser-actions/setup-chrome@v2

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - run: |
          ./gradlew --info --no-daemon ktlintCheck allTests --stacktrace
  npm:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - name: Build JS Library
        run: ./gradlew jsNodeProductionLibraryDistribution

      - name: Run npm pack
        working-directory: ./commons-js/build/dist/js/productionLibrary
        run: npm pack

      - name: Upload .tgz to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: attocash-commons-js-0.0.0-unspecified.tgz
          path: ./commons-js/build/dist/js/productionLibrary/attocash-commons-js-0.0.0-unspecified.tgz
  snapshot:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - name: release jar
        run: |
          VERSION=$(git rev-parse --short HEAD)
          ./gradlew publishToSonatype --stacktrace -P version="$VERSION-SNAPSHOT"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
