name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: opencl
        run: |
          sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd clinfo
          clinfo

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v3

      - run: |
          ./gradlew test --no-daemon --info --fail-fast
          ./gradlew build -x test

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v3

      - uses: github/codeql-action/init@v3
        with:
          languages: java

      - run: |
          ./gradlew --info build -x test -x ktlintCheck

      - uses: github/codeql-action/analyze@v3
