name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/test.yaml
  snapshot:
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - name: release snapshot
        run: |
          VERSION=$(git rev-parse --short HEAD)
          gradle publishToSonatype --stacktrace -P version=$VERSION-SNAPSHOT
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
