name: Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: opencl
        run: |
          sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd clinfo
          clinfo

      - uses: browser-actions/setup-chrome@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v4

      - run: |
          ./gradlew --info --no-daemon ktlintCheck allTests
  snapshot:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v4

      - name: release jar
        run: |
          VERSION=$(git rev-parse --short HEAD)
          ./gradlew publishToSonatype --stacktrace -P version="$VERSION-SNAPSHOT"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
