name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: opencl
        run: |
          sudo apt-get update
          sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd clinfo
          clinfo

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/gradle-build-action@v3

      - run: |
          gradle --info build
        env:
          POCL_DEVICES: "basic"
          POCL_DEBUG: "all"

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/gradle-build-action@v3

      - uses: github/codeql-action/init@v3
        with:
          languages: java

      - run: |
          gradle --info build -x test -x ktlintCheck

      - uses: github/codeql-action/analyze@v3
