name: Test
on:
  workflow_call:

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: opencl
        run: |
          sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd clinfo
          clinfo

      - uses: browser-actions/setup-chrome@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v4

      - run: |
          ./gradlew --info --no-daemon ktlintCheck allTests
